apiVersion: v2
appVersion: 7.0
name: wg-easy
version: 0.1.0
description: wg-easy description todo
dependencies:
- name: replicated-library
  repository: https://replicatedhq.github.io/helm-charts
  version: '^0.7.0'
home: https://github.com/replicatedhq/replicated-starter-helm/charts/tree/main/
kubeVersion: '>=1.20.0-0'
