{{/* Make sure all variables are set properly */}}
{{- include "replicated-library.values.setup" . }}

{{- define "hardcodedValues" -}}
{{- $wireguard := default dict .Values.wireguard -}}
{{- $password := default dict $wireguard.password -}}
apps:
  wg-easy:
    containers:
      wg-container:
        env:
          WG_HOST: {{ required "external host name is required. Set wireguard.host" $wireguard.host }}
          {{- if $wireguard.port }}
          WG_PORT: {{ $wireguard.port }}
          {{- end }}
          {{- if $wireguard.mtu }}
          WG_MTU: {{ $wireguard.mtu }}
          {{- end }}
          {{- if $wireguard.persistentKeepalive }}
          WG_PERSISTENT_KEEPALIVE: {{ $wireguard.persistentKeepalive }}
          {{- end }}
          {{- if $wireguard.defaultAddress }}
          WG_DEFAULT_ADDRESS: {{ $wireguard.defaultAddress }}
          {{- end }}
          {{- if $wireguard.defaultDns }}
          WG_DEFAULT_DNS: {{ $wireguard.defaultDns }}
          {{- end }}
          {{- if $wireguard.allowedIps }}
          WG_ALLOWED_IPS: {{ $wireguard.allowedIps }}
          {{- end }}
          {{- if $wireguard.preUp }}
          WG_PRE_UP: {{ $wireguard.preUp }}
          {{- end }}
          {{- if $wireguard.postUp }}
          WG_POST_UP: {{ $wireguard.postUp }}
          {{- end }}
          {{- if $wireguard.preDown }}
          WG_PRE_DOWN: {{ $wireguard.preDown }}
          {{- end }}
          {{- if $wireguard.postDown }}
          WG_POST_DOWN: {{ $wireguard.postDown }}
          {{- end }}
{{- if $password }}
        envFrom:
        - secretRef:
            name: {{ include "replicated-library.names.prefix" . }}-webpass
secrets:
  webpass:
    enabled: true
    data:
      PASSWORD: {{ $password }}
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "hardcodedValues" . | fromYaml) -}}
{{- include "replicated-library.all" . }}
